### ISSUE TITLE
Installation instructions incomplete

### ISSUE THREAD

**Issue by tomasdev** [flomio/flomio_ios#14]
Missing Step 7. `#import <AudioJack/AudioJack.h>` into your app controller's header file.

After that, you can use `ACRAudioJackReader* _reader` but getting:

```
Undefined symbols for architecture x86_64:
  "std::terminate()", referenced from:
      ___clang_call_terminate in libAudioJack.a(ACRAudioJackReader.o)
      ___clang_call_terminate in libAudioJack.a(aurio_helper.o)
...
```

**Comment by tomasdev** [comment]
Step 8. Add `-lc++` to Linker Flags

**Comment by flomio** [comment]
Thanks for the tip. we were just putting in a Dummy.mm file to trigger the C++ compiler to kick on but this method is much cleaner.
