### ISSUE TITLE
FloBLE Example app needs a Manual Disconnect button to multiplex readers

### ISSUE THREAD

**Issue by grundyoso** [flomio/flomio_ios#8]
https://github.com/yummytech/flomio_floble/issues/14

**Comment by jchuck627** [comment]
Added disconnect button to IOS and OS X apps.  Released in alpha 0.6, should be used with floBLE version 0x0009.  Supports sending a new disconnect_op message to floBLE, which disconnects and stops advertising.  Then disconnects self from floBLE and restarts scanning.
