### ISSUE TITLE
"FJNFCAdapter.h" ?

### ISSUE THREAD

**Issue by Natelegreat1** [flomio/flomio_ios#9]
I cannot find this file in the SDK... The integration instructions need a bit more detail.
I also do not see a FloJack group : "... all the files under the FloJack group ..."

**Comment by grundyoso** [comment]
If you're working with the FloJack v2, you want to use the ACR35 folder to build your application. The FloJack folder has currently been repurposed for the FloBLE project. It's a bit of a mess right now, but we are working to clean this repo up to avoid this type of confusion.

**Comment by flomio** [comment]
Chuck, can you rename the FloJack folder to FloBLE and just eliminate the current FloBLE folder?

**Comment by Natelegreat1** [comment]
The ACR35 folder app seems to be able to read a card (like Air Miles) but nothing seems to happen when I tap it with the tags / NFC cards. (I am using this by the way : http://flomio.com/shop/nfc-readers/flojack-nfc-reader/)
Is there an updated set of instructions on how to use the delegates w/ ACR35?
is libAudioJack.a the file I want???

**Comment by grundyoso** [comment]
The FloJack and ACR35 are hardware equivalents. That said, we are working to release a suite of applications via the App store that will work with only the FloJack. If you'd like to develop your own application you can read through the ACR35 documentation found in flomio_ios ▸ ACR35 ▸ AudioJack ▸ doc

**Comment by Natelegreat1** [comment]
Getting warmer... #import <AudioJack/AudioJack.h>
 & "ACRAudioJackReaderDelegate"  are throwing 'not found' errors in both my project and the AudioJackDemo project. libAudioJack.a is the framework, right?

**Comment by grundyoso** [comment]
copy/paste the errors here and I should be able to sort you out... libAudioJack.a is the framework... follow the instructions in the README file on how to build... I've copied them here for your convenience:  

Installation
1. To use the class library to your project, copy "AudioJackDemo\AudioJack"
   folder to your project folder and drag it to your project in the Xcode.
2. Select Build Settings tab in the Targets.
3. Add "$(PROJECT_DIR)" to the Header Search Paths.
4. Add "-ObjC" to Other Linker Flags.
5. Select Build Phases in the Targets.
6. Add "AudioToolbox.framework to Link Binary With Libraries.

**Comment by Natelegreat1** [comment]
Followed steps successfully. Thank you.

Errors: 
(MY viewController) - AudioJack/AudioJack.h file not found with <angled>; use "quotes" instead
(MY viewController) - Cannot find protocol declaration for 'ACRAudioJackReaderDelegate'
(AudioJack.h) - AudioJack/AudioJack.h:10:9: 'AudioJack/ACRCRC16.h' file not found

**Comment by grundyoso** [comment]
Those errors have to do with how you've pulled the ACR35 files into your project. The proper way would have been to drag the entire "AudioJack" folder into your project pane such that the file structure would remain.. hence the "AudioJack/AudioJack.h" style paths. If you have all the header files intermingled with you source files without the "AudioJack" folder containing them, then you need to remove the <> and replace with "" leaving out the "AudioJack" folder mention... 

Example:

#import "ACRCRC16.h"
#import "ACRAudioJackReader.h"
#import "ACRResult.h"
#import "ACRStatus.h"
#import "ACRTrack1Data.h"
#import "ACRTrack2Data.h"
#import "ACRTrackData.h"
#import "ACRAesTrackData.h"
#import "ACRDukptTrackData.h"
#import "ACRDukptReceiver.h"
#import "AudioJackErrors.h"

**Comment by Natelegreat1** [comment]
This is what I did. I dragged the entire folder into the Project yet also within the parent folder directory.
If I change the ""s for <>, the errors go away...until the compiler shoots out : 
```(null): "std::terminate()", referenced from:
(null): "___gxx_personality_v0", referenced from:
(null): "___cxa_allocate_exception", referenced from:
(null): "___cxa_throw", referenced from:
(null): "___cxa_begin_catch", referenced from:
(null): "vtable for __cxxabiv1::__class_type_info", referenced from:
(null): "___cxa_end_catch", referenced from:
(null): Linker command failed with exit code 1 (use -v to see invocation)```

**Comment by grundyoso** [comment]
hmm, those I don't think I've seen before... do you have a Dummy.mm file in your project?  This is meant to force the C++ compiler to engage the project and a must have for the build to work.

**Comment by jchuck627** [comment]
Ok.
Chuck

**Comment by Natelegreat1** [comment]
Did not know I needed Dummy.mm !
Compiles successfully. :+1:
